# Generated by Django 4.2.27 on 2026-01-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecustomuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
