# Generated by Django 4.2.27 on 2026-01-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_basecustomuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='person_code',
            field=models.CharField(default='6', max_length=6, unique=True),
        ),
    ]
