# Generated by Django 4.2.27 on 2026-02-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('account', '0004_basecustomuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.departement'),
        ),
        migrations.AddField(
            model_name='basecustomuser',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.hospital'),
        ),
    ]
