# Generated by Django 4.2.27 on 2026-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_basecustomuser_person_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='person_code',
            field=models.CharField(blank=True, default='360778', max_length=6, null=True, unique=True),
        ),
    ]
