# Generated by Django 4.2.27 on 2026-02-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('account', '0005_basecustomuser_departement_basecustomuser_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecustomuser',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='basecustomuser',
            name='hospital',
        ),
        migrations.AddField(
            model_name='basecustomuser',
            name='departement',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.departement'),
        ),
        migrations.AddField(
            model_name='basecustomuser',
            name='hospital',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.hospital'),
        ),
    ]
