# Generated by Django 4.2.27 on 2026-01-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_roles_status_alter_basecustomuser_person_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
