# Generated by Django 4.2.27 on 2026-01-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
        ('account', '0007_delete_roles_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='role', to='Person.status'),
        ),
        migrations.AddField(
            model_name='basecustomuser',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='status', to='Person.status'),
        ),
    ]
