# Generated by Django 4.2.27 on 2026-02-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_basecustomuser_person_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.status'),
        ),
    ]
