# Generated by Django 4.2.27 on 2026-01-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
        ('account', '0008_basecustomuser_role_basecustomuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='role', to='Person.role'),
        ),
    ]
