# Generated by Django 4.2.27 on 2026-02-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_basecustomuser_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
