# Generated by Django 4.2.27 on 2026-02-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_userhospitalmembership'),
        ('account', '0011_remove_basecustomuser_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='hospital',
            field=models.ManyToManyField(through='hospital.UserHospitalMembership', to='hospital.hospital'),
        ),
    ]
