# Generated by Django 4.2.27 on 2026-02-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_basecustomuser_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecustomuser',
            name='role',
        ),
    ]
