# Generated by Django 4.2.27 on 2026-02-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_basecustomuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecustomuser',
            name='departement',
        ),
    ]
