# Generated by Django 6.0.2 on 2026-02-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_basecustomuser_departement'),
        ('hospital', '0009_alter_patientadmission_discharged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='hospital',
            field=models.ManyToManyField(through='hospital.UserHospitalMembership', through_fields=('user', 'hospital'), to='hospital.hospital'),
        ),
    ]
