# Generated by Django 4.2.27 on 2026-02-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_basecustomuser_status'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.status'),
        ),
    ]
