# Generated by Django 4.2.27 on 2026-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_alter_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
