# Generated by Django 4.2.27 on 2026-02-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_alter_patient_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Femail')], default='Male', max_length=8),
        ),
    ]
