# Generated by Django 4.2.27 on 2026-02-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('Person', '0005_patient_departement_patient_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.AddField(
            model_name='patient',
            name='departement',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.departement'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.hospital'),
        ),
    ]
