# Generated by Django 4.2.27 on 2026-02-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0006_remove_patient_departement_remove_patient_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='person_code',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
