# Generated by Django 4.2.27 on 2026-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('Person', '0008_alter_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='departement',
            field=models.ManyToManyField(blank=True, to='hospital.departement'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ManyToManyField(blank=True, to='hospital.hospital'),
        ),
    ]
