# Generated by Django 4.2.27 on 2026-02-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0009_alter_patient_departement_alter_patient_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
