# Generated by Django 4.2.27 on 2026-02-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0010_alter_patient_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
    ]
