# Generated by Django 4.2.27 on 2026-02-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0011_remove_patient_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='departement',
        ),
    ]
