# Generated by Django 4.2.27 on 2026-02-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_patientadmission'),
        ('Person', '0012_remove_patient_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission',
            field=models.ManyToManyField(through='hospital.PatientAdmission', to='hospital.hospital'),
        ),
    ]
