# Generated by Django 4.2.27 on 2026-02-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_drugs_visit'),
        ('Person', '0013_patient_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='hospital.visit'),
        ),
    ]
