# Generated by Django 6.0.2 on 2026-02-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0015_remove_patient_visits_visit'),
        ('hospital', '0009_alter_patientadmission_discharged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admission',
            field=models.ManyToManyField(through='hospital.PatientAdmission', through_fields=('patient', 'hospital'), to='hospital.hospital'),
        ),
    ]
