# Generated by Django 4.2.27 on 2026-02-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_userhospitalmembership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHospitalMembership',
        ),
    ]
