# Generated by Django 4.2.27 on 2026-02-06 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0013_patient_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0006_patientadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField()),
                ('visit_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.departement')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('drugs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.drugs')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Person.patient')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
