# Generated by Django 4.2.27 on 2026-02-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0015_remove_patient_visits_visit'),
        ('hospital', '0007_drugs_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='drugs',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Drugs',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
