# Generated by Django 6.0.2 on 2026-02-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_visit_created_by_remove_visit_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmission',
            name='discharged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userhospitalmembership',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.departement'),
        ),
    ]
